### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by lmc2000** [openai/point-e#107]
0it [00:02, ?it/s]
Traceback (most recent call last):
  File "D:\Users\Limc\Downloads\point-e-main\point_e\测试运行point_e.py", line 49, in <module>
    for x in tqdm(sampler.sample_batch_progressive(batch_size=1, model_kwargs=dict(images=[img]))):
  File "D:\DevelopTools\anaconda3\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "D:\Users\Limc\Downloads\point-e-main\point_e\diffusion\sampler.py", line 163, in sample_batch_progressive
    for x in samples_it:
  File "D:\Users\Limc\Downloads\point-e-main\point_e\diffusion\k_diffusion.py", line 182, in karras_sample_progressive
    for obj in sample_fn(
  File "D:\DevelopTools\anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "D:\Users\Limc\Downloads\point-e-main\point_e\diffusion\k_diffusion.py", line 266, in sample_heun
    denoised = denoiser(x, sigma_hat * s_in)
  File "D:\Users\Limc\Downloads\point-e-main\point_e\diffusion\k_diffusion.py", line 174, in guided_denoiser
    x_0 = denoiser(x_t, sigma)
  File "D:\Users\Limc\Downloads\point-e-main\point_e\diffusion\k_diffusion.py", line 161, in denoiser
    _, denoised = model.denoise(
  File "D:\Users\Limc\Downloads\point-e-main\point_e\diffusion\k_diffusion.py", line 100, in denoise
    t = th.tensor(
TypeError: 'float' object cannot be interpreted as an integer

**Comment by hjwdzh** [comment]
I meet the same problem and simply apply an integer conversion to sigma_to_t result. Not sure whether it will be the correct solution.

**Comment by lmc2000** [comment]
Thank you, the problem has been solved.
