### ISSUE TITLE
Jupyter kernel crash text2pointcloud.ipynb 

### ISSUE THREAD

**Issue by MSDNAndi** [openai/point-e#26]
Running into a Jupyter kernel crash in last cell.
I tried to set KMP_DUPLICATE_LIB_OK=true to see if it changes anything, but no difference.

Output copy/pasted:
info 23:47:26.002: Loading webview. View is notset
info 23:47:26.003: Loading web view...
info 23:47:26.004: Webview panel created.
info 23:47:26.414: Web view react rendered
warn 23:47:59.496: StdErr from Kernel Process OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

error 23:48:00.563: Disposing session as kernel process died ExitCode: 3, Reason: c:\Users\andre\anaconda3\envs\point-e\lib\site-packages\traitlets\traitlets.py:2547: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
c:\Users\andre\anaconda3\envs\point-e\lib\site-packages\traitlets\traitlets.py:2498: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '06a75dfe-7f86-4306-9e7d-773b07153587' instead of 'b"06a75dfe-7f86-4306-9e7d-773b07153587"'.
  warn(
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

info 23:48:00.563: Dispose Kernel process 43428.
error 23:48:00.564: Raw kernel process exited code: 3
error 23:48:00.566: Error in waiting for cell to complete Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (c:\Users\andre\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.1003441034\out\extension.node.js:2:32353)
    at c:\Users\andre\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.1003441034\out\extension.node.js:2:51405
    at Map.forEach (<anonymous>)
    at y._clearKernelState (c:\Users\andre\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.1003441034\out\extension.node.js:2:51390)
    at y.dispose (c:\Users\andre\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.1003441034\out\extension.node.js:2:44872)
    at c:\Users\andre\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.1003441034\out\extension.node.js:2:2181854
    at t.swallowExceptions (c:\Users\andre\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.1003441034\out\extension.node.js:7:108503)
    at p.dispose (c:\Users\andre\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.1003441034\out\extension.node.js:2:2181832)
    at t.RawSession.dispose (c:\Users\andre\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.1003441034\out\extension.node.js:2:2186853)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
warn 23:48:00.567: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 23:48:00.568: Cancel all remaining cells true || Error || undefined

**Comment by mooresethmoore** [comment]
I fixed this by adding the following cell **before** importing torch and tdqm, let me know if it works. 

import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

**Comment by xmario3** [comment]
> I fixed this by adding the following cell **before** importing torch and tdqm, let me know if it works.
> 
> import os os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

It worked for me!
nice!

Please do a request!
